# Generated by Django 5.0.3 on 2024-03-27 13:09

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_reservation_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="play",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.play_image_file_path
            ),
        ),
    ]
